### ISSUE TITLE
Error: Threshold of 70 not met with score of 60

### ISSUE THREAD

**Issue by paulmaunders** [addyosmani/psi#79]
When I run the cli version of psi on certain sites, I am getting an error.

```$ psi bbc.com

--------------------------------------------------------

URL:       bbc.com
Strategy:  mobile
Speed:     69
Usability: 98

CSS size                                   | 271 kB
HTML size                                  | 209 kB
Image size                                 | 125 kB
JavaScript size                            | 1.49 MB
CSS resources                              | 8
Hosts                                      | 27
JS resources                               | 33
Resources                                  | 80
Static resources                           | 54
Other size                                 | 4.44 kB
Total size of request bytes sent           | 15 kB

Enable GZIP compression                    | 0.56
Leverage browser caching                   | 7.19
Minimize render blocking resources         | 32
Optimize images                            | 6.16
Size tap targets appropriately             | 1.03

--------------------------------------------------------

Error: Threshold of 70 not met with score of 69
    at Promise.resolve.then (/usr/local/lib/node_modules/psi/lib/output.js:93:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)```

**Comment by sindresorhus** [comment]
It's the default threshold. You can set your own. Read more here: https://github.com/addyosmani/psi#threshold
